language: python
python:
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - python setup.py install
  - pytest
  - coverage run -m pytest --cov=pyDeltaRCM tests/
  - coverage report -m

after_success:
  - coveralls
