language: python
python:
  - "3.6"
  - "3.8"

install:
  - pip install pytest
  - pip install -r requirements.txt

script:
  - python setup.py install
  - pytest

jobs:
  include:
    - stage: coverage
      python: "3.8"
      install: 
        - pip install -r requirements.txt 
        - pip install -e .
        - pip install pytest pytest-cov coveralls
      script: pytest --cov=pyDeltaRCM/
      after_success: 
        - coveralls
    - stage: docs
      python: "3.8"
      install: 
        - pip install -r requirements.txt
        - pip install -e .
        - pip install sphinx sphinx-automodapi
        - sudo apt update -y && sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
      script:
        - (cd docs && sphinx-build -E -W -b linkcheck source build) 
        - (cd docs && make html)
      deploy:
        provider: pages:git
        github_token: $GITHUB_TOKEN
        committer_from_gh: true
        verbose: true
        edge: true
        local-dir: docs/build/html
        on:
          branch: develop