language: python
python:
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install pytest
# command to run tests
script:
  - python setup.py install
  - pytest

jobs:
  include:
    - stage: coverage
      python: "3.8"
      install: 
        - pip install -r requirements.txt 
        - pip install pytest
        - pip install pytest-cov
        - pip install coveralls
      script: pytest --cov=pyDeltaRCM_WMT/
      after_success: 
        - coveralls
