out_dir:
  type: 'str'
  default: 'deltaRCM_Output'
verbose:
  type: 'int'
  default: 0
seed:
  type: ['int', 'None']
  default: null
Length:
  type: ['float', 'int']
  default: 1000.
Width:
  type: ['float', 'int']
  default: 2000.
dx:
  type: ['float', 'int']
  default: 50.
L0_meters:
  type: ['float', 'int']
  default: 150.0
S0:
  type: ['float', 'int']
  default: 0.0002
itermax:
  type: 'int'
  default: 1
Np_water:
  type: 'int'
  default: 2000
u0:
  type: ['float', 'int']
  default: 1.0
N0_meters:
  type: ['float', 'int']
  default: 200.0
h0:
  type: ['float', 'int']
  default: 5.0
H_SL:
  type: ['float', 'int']
  default: 0.0
SLR:
  type: ['float', 'int']
  default: 0.0
Np_sed:
  type: 'int'
  default: 1000
f_bedload:
  type: ['float', 'int']
  default: 0.5
C0_percent:
  type: ['float', 'int']
  default: 0.1
Csmooth:
  type: ['float', 'int']
  default: 0.9
toggle_subsidence:
  type: 'bool'
  default: False
theta1:
  type: ['float', 'int']
  default: -1.0471975511965976
theta2:
  type: ['float', 'int']
  default: 1.0471975511965976
sigma_max:
  type: ['float', 'int']
  default: 2e-9
start_subsidence:
  type: ['float', 'int']
  default: 216000
bedrock:
  type: 'bool'
  default: False
bedrock_depth:
  type: ['float', 'int', 'None']
  default: null
lithification:
  type: 'bool'
  default: False
save_eta_figs:
  type: 'bool'
  default: False
save_stage_figs:
  type: 'bool'
  default: False
save_depth_figs:
  type: 'bool'
  default: False
save_discharge_figs:
  type: 'bool'
  default: False
save_velocity_figs:
  type: 'bool'
  default: False
save_sedflux_figs:
  type: 'bool'
  default: False
save_figs_sequential:
  type: 'bool'
  default: True
save_metadata:
  type: 'bool'
  default: False
save_eta_grids:
  type: 'bool'
  default: False
save_stage_grids:
  type: 'bool'
  default: False
save_depth_grids:
  type: 'bool'
  default: False
save_discharge_grids:
  type: 'bool'
  default: False
save_velocity_grids:
  type: 'bool'
  default: False
save_sedflux_grids:
  type: 'bool'
  default: False
save_discharge_components:
  type: 'bool'
  default: False
save_velocity_components:
  type: 'bool'
  default: False
save_dt:
  type: 'int'
  default: 86400
checkpoint_dt:
  type: ['int', 'None']
  default: null
save_strata:
  type: 'bool'
  default: True
save_checkpoint:
  type: 'bool'
  default: False
resume_checkpoint:
  type: 'bool'
  default: False
omega_sfc:
  type: ['float', 'int']
  default: 0.1
omega_flow:
  type: ['float', 'int']
  default: 0.9
Nsmooth:
  type: 'int'
  default: 5
theta_water:
  type: ['float', 'int']
  default: 1.0
coeff_theta_sand:
  type: ['float', 'int']
  default: 2.0
coeff_theta_mud:
  type: ['float', 'int']
  default: 1.0
beta:
  type: 'int'
  default: 3
sed_lag:
  type: ['float', 'int']
  default: 1.0
coeff_U_dep_mud:
  type: ['float', 'int']
  default: 0.3
coeff_U_ero_mud:
  type: ['float', 'int']
  default: 1.5
coeff_U_ero_sand:
  type: ['float', 'int']
  default: 1.05
alpha:
  type: ['float', 'int']
  default: 0.1
stepmax:
  type: ['float', 'int', 'None']
  default: null
