# This workflow build and deploys the docs
# build docs on any pull request against develop, but only deploy docs on push to develop.

name: actions

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-docs.txt
        sudo apt update -y && sudo apt install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended dvipng
      script:
        - 
    - name: Install pyDeltaRCM
      run: |
        python setup.py install
    - name: Build and test documentation
      run: |
        (cd docs && make docs)
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.5
      on:
        push:
          branches:
            - develop
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs/build/html
          GIT_CONFIG_NAME: deltarcm-helper
      
      
